# -*- coding: utf-8 -*-
"""
seasons.py — European Cup fixture data, Classic Era.

Each season is a dict. Each tie carries RSSSF's own printed aggregate in `agg`
so build_database.py can verify, automatically, that the individual legs entered
here reproduce that total exactly. If a leg is mistyped, the build fails loudly
rather than shipping a wrong scoreline.

Leg format (a tuple):
    (home_key, away_key, home_score, away_score)
    (home_key, away_key, home_score, away_score, extras_dict)

extras_dict may contain: "venue", "date" (ISO), "att", "ref", "aet" (True),
                "home_pens", "away_pens" (shootout scores).

Tie format (a dict):
    t1, t2      club keys (t1 = first-named side / first-leg host)
    win         winner club key (or None)
    by          'aggregate' | 'away_goals' | 'replay' | 'penalties' |
                'coin_toss' | 'single_match' | 'walkover' | 'bye'
    agg         (t1_goals, t2_goals) over legs 1 & 2 only — RSSSF's printed
                aggregate. None for walkovers/byes with no legs.
    legs        list of leg tuples (a 3rd leg is a play-off/replay)
    note        optional string

All results transcribed from RSSSF (James M. Ross's European competitions pages).
"""

# Short aliases so the leg tuples stay readable.
def L(home, away, hs, as_, **extras):
    return (home, away, hs, as_, extras) if extras else (home, away, hs, as_)


SEASONS = [

    # =====================================================================
    # 1955-56 — inaugural season
    # =====================================================================
    {
        "lineage": "European Cup", "season_label": "1955-56", "start_year": 1955,
        "competition_name": "European Cup",
        "winner": "real_madrid", "runner_up": "reims", "away_goals_active": False,
        "notes": "Inaugural edition. 16 invited clubs. Away-goals rule not yet in use.",
        "rounds": [
            {"name": "First Round", "ties": [
                {"t1": "servette", "t2": "real_madrid", "win": "real_madrid", "by": "aggregate", "agg": (0, 7),
                 "legs": [L("servette", "real_madrid", 0, 2), L("real_madrid", "servette", 5, 0)]},
                {"t1": "sporting_cp", "t2": "partizan", "win": "partizan", "by": "aggregate", "agg": (5, 8),
                 "legs": [L("sporting_cp", "partizan", 3, 3), L("partizan", "sporting_cp", 5, 2)]},
                {"t1": "rapid_wien", "t2": "psv", "win": "rapid_wien", "by": "aggregate", "agg": (6, 2),
                 "legs": [L("rapid_wien", "psv", 6, 1), L("psv", "rapid_wien", 1, 0)]},
                {"t1": "milan", "t2": "saarbrucken", "win": "milan", "by": "aggregate", "agg": (7, 5),
                 "legs": [L("milan", "saarbrucken", 3, 4), L("saarbrucken", "milan", 1, 4)]},
                {"t1": "rw_essen", "t2": "hibernian", "win": "hibernian", "by": "aggregate", "agg": (1, 5),
                 "legs": [L("rw_essen", "hibernian", 0, 4), L("hibernian", "rw_essen", 1, 1)]},
                {"t1": "djurgarden", "t2": "gwardia", "win": "djurgarden", "by": "aggregate", "agg": (4, 1),
                 "legs": [L("djurgarden", "gwardia", 0, 0), L("gwardia", "djurgarden", 1, 4)]},
                {"t1": "mtk", "t2": "anderlecht", "win": "mtk", "by": "aggregate", "agg": (10, 4),
                 "legs": [L("mtk", "anderlecht", 6, 3), L("anderlecht", "mtk", 1, 4)],
                 "note": "MTK competed as Vörös Lobogó this season."},
                {"t1": "agf", "t2": "reims", "win": "reims", "by": "aggregate", "agg": (2, 4),
                 "legs": [L("agf", "reims", 0, 2, venue="Copenhagen (1st leg relocated)"),
                          L("reims", "agf", 2, 2)]},
            ]},
            {"name": "Quarter-Finals", "ties": [
                {"t1": "real_madrid", "t2": "partizan", "win": "real_madrid", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("real_madrid", "partizan", 4, 0), L("partizan", "real_madrid", 3, 0)]},
                {"t1": "rapid_wien", "t2": "milan", "win": "milan", "by": "aggregate", "agg": (3, 8),
                 "legs": [L("rapid_wien", "milan", 1, 1), L("milan", "rapid_wien", 7, 2)]},
                {"t1": "djurgarden", "t2": "hibernian", "win": "hibernian", "by": "aggregate", "agg": (1, 4),
                 "legs": [L("djurgarden", "hibernian", 1, 3, venue="Glasgow, Firhill (1st leg relocated)"),
                          L("hibernian", "djurgarden", 1, 0)]},
                {"t1": "reims", "t2": "mtk", "win": "reims", "by": "aggregate", "agg": (8, 6),
                 "legs": [L("reims", "mtk", 4, 2, venue="Paris"), L("mtk", "reims", 4, 4)]},
            ]},
            {"name": "Semi-Finals", "ties": [
                {"t1": "real_madrid", "t2": "milan", "win": "real_madrid", "by": "aggregate", "agg": (5, 4),
                 "legs": [L("real_madrid", "milan", 4, 2), L("milan", "real_madrid", 2, 1)]},
                {"t1": "reims", "t2": "hibernian", "win": "reims", "by": "aggregate", "agg": (3, 0),
                 "legs": [L("reims", "hibernian", 2, 0, venue="Paris"), L("hibernian", "reims", 0, 1)]},
            ]},
            {"name": "Final", "ties": [
                {"t1": "real_madrid", "t2": "reims", "win": "real_madrid", "by": "single_match", "agg": (4, 3),
                 "legs": [L("real_madrid", "reims", 4, 3, venue="Parc des Princes, Paris",
                            date="1956-06-13", att=38239, ref="Arthur Ellis (England)")]},
            ]},
        ],
    },

    # =====================================================================
    # 1956-57
    # =====================================================================
    {
        "lineage": "European Cup", "season_label": "1956-57", "start_year": 1956,
        "competition_name": "European Cup",
        "winner": "real_madrid", "runner_up": "fiorentina", "away_goals_active": False,
        "notes": "22 clubs. Level ties settled by a play-off on neutral ground.",
        "rounds": [
            {"name": "Preliminary Round", "ties": [
                {"t1": "agf", "t2": "nice", "win": "nice", "by": "aggregate", "agg": (2, 6),
                 "legs": [L("agf", "nice", 1, 1, venue="Copenhagen (1st leg relocated)"),
                          L("nice", "agf", 5, 1)]},
                {"t1": "porto", "t2": "bilbao", "win": "bilbao", "by": "aggregate", "agg": (3, 5),
                 "legs": [L("porto", "bilbao", 1, 2), L("bilbao", "porto", 3, 2)]},
                {"t1": "anderlecht", "t2": "man_utd", "win": "man_utd", "by": "aggregate", "agg": (0, 12),
                 "legs": [L("anderlecht", "man_utd", 0, 2), L("man_utd", "anderlecht", 10, 0)]},
                {"t1": "dortmund", "t2": "spora", "win": "dortmund", "by": "replay", "agg": (5, 5),
                 "legs": [L("dortmund", "spora", 4, 3), L("spora", "dortmund", 2, 1),
                          L("dortmund", "spora", 7, 0, venue="Dortmund (play-off)")]},
                {"t1": "dinamo_buc", "t2": "galatasaray", "win": "dinamo_buc", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("dinamo_buc", "galatasaray", 3, 1), L("galatasaray", "dinamo_buc", 2, 1)]},
                {"t1": "slovan", "t2": "cwks_warsaw", "win": "slovan", "by": "aggregate", "agg": (4, 2),
                 "legs": [L("slovan", "cwks_warsaw", 4, 0), L("cwks_warsaw", "slovan", 2, 0)]},
            ]},
            {"name": "First Round", "ties": [
                {"t1": "real_madrid", "t2": "rapid_wien", "win": "real_madrid", "by": "replay", "agg": (5, 5),
                 "legs": [L("real_madrid", "rapid_wien", 4, 2), L("rapid_wien", "real_madrid", 3, 1),
                          L("real_madrid", "rapid_wien", 2, 0, venue="Madrid (play-off)")]},
                {"t1": "rangers", "t2": "nice", "win": "nice", "by": "replay", "agg": (3, 3),
                 "legs": [L("rangers", "nice", 2, 1), L("nice", "rangers", 2, 1),
                          L("rangers", "nice", 1, 3, venue="Paris (play-off)")]},
                {"t1": "bilbao", "t2": "honved", "win": "bilbao", "by": "aggregate", "agg": (6, 5),
                 "legs": [L("bilbao", "honved", 3, 2),
                          L("honved", "bilbao", 3, 3, venue="Brussels (Honvéd home leg relocated)")]},
                {"t1": "man_utd", "t2": "dortmund", "win": "man_utd", "by": "aggregate", "agg": (3, 2),
                 "legs": [L("man_utd", "dortmund", 3, 2), L("dortmund", "man_utd", 0, 0)]},
                {"t1": "rapid_jc", "t2": "red_star", "win": "red_star", "by": "aggregate", "agg": (3, 6),
                 "legs": [L("rapid_jc", "red_star", 3, 4, venue="Kerkrade (1st leg)"),
                          L("red_star", "rapid_jc", 2, 0)]},
                {"t1": "cdna_sofia", "t2": "dinamo_buc", "win": "cdna_sofia", "by": "aggregate", "agg": (10, 4),
                 "legs": [L("cdna_sofia", "dinamo_buc", 8, 1), L("dinamo_buc", "cdna_sofia", 3, 2)]},
                {"t1": "slovan", "t2": "grasshopper", "win": "grasshopper", "by": "aggregate", "agg": (1, 2),
                 "legs": [L("slovan", "grasshopper", 1, 0),
                          L("grasshopper", "slovan", 2, 0, venue="Munich (2nd leg relocated)")]},
                {"t1": "fiorentina", "t2": "ifk_norr", "win": "fiorentina", "by": "aggregate", "agg": (2, 1),
                 "legs": [L("fiorentina", "ifk_norr", 1, 1),
                          L("ifk_norr", "fiorentina", 0, 1, venue="Rome (2nd leg relocated)")]},
            ]},
            {"name": "Quarter-Finals", "ties": [
                {"t1": "real_madrid", "t2": "nice", "win": "real_madrid", "by": "aggregate", "agg": (6, 2),
                 "legs": [L("real_madrid", "nice", 3, 0), L("nice", "real_madrid", 2, 3)]},
                {"t1": "bilbao", "t2": "man_utd", "win": "man_utd", "by": "aggregate", "agg": (5, 6),
                 "legs": [L("bilbao", "man_utd", 5, 3), L("man_utd", "bilbao", 3, 0)]},
                {"t1": "red_star", "t2": "cdna_sofia", "win": "red_star", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("red_star", "cdna_sofia", 3, 1), L("cdna_sofia", "red_star", 2, 1)]},
                {"t1": "fiorentina", "t2": "grasshopper", "win": "fiorentina", "by": "aggregate", "agg": (5, 3),
                 "legs": [L("fiorentina", "grasshopper", 3, 1), L("grasshopper", "fiorentina", 2, 2)]},
            ]},
            {"name": "Semi-Finals", "ties": [
                {"t1": "real_madrid", "t2": "man_utd", "win": "real_madrid", "by": "aggregate", "agg": (5, 3),
                 "legs": [L("real_madrid", "man_utd", 3, 1), L("man_utd", "real_madrid", 2, 2)]},
                {"t1": "red_star", "t2": "fiorentina", "win": "fiorentina", "by": "aggregate", "agg": (0, 1),
                 "legs": [L("red_star", "fiorentina", 0, 1), L("fiorentina", "red_star", 0, 0)]},
            ]},
            {"name": "Final", "ties": [
                {"t1": "real_madrid", "t2": "fiorentina", "win": "real_madrid", "by": "single_match", "agg": (2, 0),
                 "legs": [L("real_madrid", "fiorentina", 2, 0, venue="Estadio Santiago Bernabéu, Madrid",
                            date="1957-05-30", att=124000, ref="Leo Horn (Netherlands)")]},
            ]},
        ],
    },

    # =====================================================================
    # 1957-58
    # =====================================================================
    {
        "lineage": "European Cup", "season_label": "1957-58", "start_year": 1957,
        "competition_name": "European Cup",
        "winner": "real_madrid", "runner_up": "milan", "away_goals_active": False,
        "notes": "24 clubs. Manchester United's campaign overshadowed by the Munich air disaster.",
        "rounds": [
            {"name": "First Round", "ties": [
                {"t1": "sevilla", "t2": "benfica", "win": "sevilla", "by": "aggregate", "agg": (3, 1),
                 "legs": [L("sevilla", "benfica", 3, 1), L("benfica", "sevilla", 0, 0)]},
                {"t1": "agf", "t2": "glenavon", "win": "agf", "by": "aggregate", "agg": (3, 0),
                 "legs": [L("agf", "glenavon", 0, 0), L("glenavon", "agf", 0, 3, venue="Belfast (2nd leg)")]},
                {"t1": "cdna_sofia", "t2": "vasas", "win": "vasas", "by": "aggregate", "agg": (3, 7),
                 "legs": [L("cdna_sofia", "vasas", 2, 1), L("vasas", "cdna_sofia", 6, 1)]},
                {"t1": "gwardia", "t2": "wismut", "win": "wismut", "by": "coin_toss", "agg": (4, 4),
                 "legs": [L("gwardia", "wismut", 3, 1), L("wismut", "gwardia", 3, 1, venue="Aue (2nd leg)"),
                          L("gwardia", "wismut", 1, 1, venue="East Berlin (play-off)")],
                 "note": "Wismut progressed on the toss of a coin after the play-off finished level."},
                {"t1": "shamrock", "t2": "man_utd", "win": "man_utd", "by": "aggregate", "agg": (2, 9),
                 "legs": [L("shamrock", "man_utd", 0, 6), L("man_utd", "shamrock", 3, 2)]},
                {"t1": "dudelange", "t2": "red_star", "win": "red_star", "by": "aggregate", "agg": (1, 14),
                 "legs": [L("dudelange", "red_star", 0, 5, venue="Luxembourg City (1st leg)"),
                          L("red_star", "dudelange", 9, 1)]},
                {"t1": "rangers", "t2": "st_etienne", "win": "rangers", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("rangers", "st_etienne", 3, 1), L("st_etienne", "rangers", 2, 1)]},
                {"t1": "milan", "t2": "rapid_wien", "win": "milan", "by": "replay", "agg": (6, 6),
                 "legs": [L("milan", "rapid_wien", 4, 1), L("rapid_wien", "milan", 5, 2),
                          L("milan", "rapid_wien", 4, 2, venue="Zürich (play-off)")]},
            ]},
            {"name": "Second Round", "ties": [
                {"t1": "antwerp", "t2": "real_madrid", "win": "real_madrid", "by": "aggregate", "agg": (1, 8),
                 "legs": [L("antwerp", "real_madrid", 1, 2), L("real_madrid", "antwerp", 6, 0)]},
                {"t1": "sevilla", "t2": "agf", "win": "sevilla", "by": "aggregate", "agg": (4, 2),
                 "legs": [L("sevilla", "agf", 4, 0), L("agf", "sevilla", 2, 0)]},
                {"t1": "wismut", "t2": "ajax", "win": "ajax", "by": "aggregate", "agg": (1, 4),
                 "legs": [L("wismut", "ajax", 1, 3, venue="Aue (1st leg)"), L("ajax", "wismut", 1, 0)]},
                {"t1": "young_boys", "t2": "vasas", "win": "vasas", "by": "aggregate", "agg": (2, 3),
                 "legs": [L("young_boys", "vasas", 1, 1, venue="Geneva (1st leg)"),
                          L("vasas", "young_boys", 2, 1)]},
                {"t1": "man_utd", "t2": "dukla", "win": "man_utd", "by": "aggregate", "agg": (3, 1),
                 "legs": [L("man_utd", "dukla", 3, 0), L("dukla", "man_utd", 1, 0)]},
                {"t1": "ifk_norr", "t2": "red_star", "win": "red_star", "by": "aggregate", "agg": (3, 4),
                 "legs": [L("ifk_norr", "red_star", 2, 2), L("red_star", "ifk_norr", 2, 1)]},
                {"t1": "dortmund", "t2": "cca_buc", "win": "dortmund", "by": "replay", "agg": (5, 5),
                 "legs": [L("dortmund", "cca_buc", 4, 2), L("cca_buc", "dortmund", 3, 1),
                          L("dortmund", "cca_buc", 3, 1, venue="Bologna (play-off)")]},
                {"t1": "rangers", "t2": "milan", "win": "milan", "by": "aggregate", "agg": (1, 6),
                 "legs": [L("rangers", "milan", 1, 4), L("milan", "rangers", 2, 0)]},
            ]},
            {"name": "Quarter-Finals", "ties": [
                {"t1": "real_madrid", "t2": "sevilla", "win": "real_madrid", "by": "aggregate", "agg": (10, 2),
                 "legs": [L("real_madrid", "sevilla", 8, 0), L("sevilla", "real_madrid", 2, 2)]},
                {"t1": "ajax", "t2": "vasas", "win": "vasas", "by": "aggregate", "agg": (2, 6),
                 "legs": [L("ajax", "vasas", 2, 2), L("vasas", "ajax", 4, 0)]},
                {"t1": "man_utd", "t2": "red_star", "win": "man_utd", "by": "aggregate", "agg": (5, 4),
                 "legs": [L("man_utd", "red_star", 2, 1), L("red_star", "man_utd", 3, 3)],
                 "note": "The return in Belgrade was Manchester United's last match before the Munich air disaster."},
                {"t1": "dortmund", "t2": "milan", "win": "milan", "by": "aggregate", "agg": (2, 5),
                 "legs": [L("dortmund", "milan", 1, 1), L("milan", "dortmund", 4, 1)]},
            ]},
            {"name": "Semi-Finals", "ties": [
                {"t1": "real_madrid", "t2": "vasas", "win": "real_madrid", "by": "aggregate", "agg": (4, 2),
                 "legs": [L("real_madrid", "vasas", 4, 0), L("vasas", "real_madrid", 2, 0)]},
                {"t1": "man_utd", "t2": "milan", "win": "milan", "by": "aggregate", "agg": (2, 5),
                 "legs": [L("man_utd", "milan", 2, 1), L("milan", "man_utd", 4, 0)]},
            ]},
            {"name": "Final", "ties": [
                {"t1": "real_madrid", "t2": "milan", "win": "real_madrid", "by": "single_match", "agg": (3, 2),
                 "legs": [L("real_madrid", "milan", 3, 2, venue="Heysel Stadium, Brussels",
                            date="1958-05-28", att=67000, ref="Alsteen (Belgium)", aet=True)]},
            ]},
        ],
    },

    # =====================================================================
    # 1958-59
    # =====================================================================
    {
        "lineage": "European Cup", "season_label": "1958-59", "start_year": 1958,
        "competition_name": "European Cup",
        "winner": "real_madrid", "runner_up": "reims", "away_goals_active": False,
        "notes": "A qualifying round is added. Several ties settled by play-off.",
        "rounds": [
            {"name": "Qualifying Round", "ties": [
                {"t1": "juventus", "t2": "wiener_sc", "win": "wiener_sc", "by": "aggregate", "agg": (3, 8),
                 "legs": [L("juventus", "wiener_sc", 3, 1), L("wiener_sc", "juventus", 7, 0)]},
                {"t1": "dinamo_zagreb", "t2": "dukla", "win": "dukla", "by": "aggregate", "agg": (3, 4),
                 "legs": [L("dinamo_zagreb", "dukla", 2, 2), L("dukla", "dinamo_zagreb", 2, 1)]},
                {"t1": "kb_copenhagen", "t2": "schalke", "win": "schalke", "by": "replay", "agg": (5, 5),
                 "legs": [L("kb_copenhagen", "schalke", 3, 0), L("schalke", "kb_copenhagen", 5, 2),
                          L("kb_copenhagen", "schalke", 1, 3, venue="Enschede (play-off)")]},
                {"t1": "atletico", "t2": "drumcondra", "win": "atletico", "by": "aggregate", "agg": (13, 1),
                 "legs": [L("atletico", "drumcondra", 8, 0), L("drumcondra", "atletico", 1, 5)]},
                {"t1": "wismut", "t2": "petrolul", "win": "wismut", "by": "replay", "agg": (4, 4),
                 "legs": [L("wismut", "petrolul", 4, 2, venue="Aue (1st leg)"),
                          L("petrolul", "wismut", 2, 0),
                          L("wismut", "petrolul", 4, 0, venue="Kiev (play-off)")]},
                {"t1": "jeunesse", "t2": "ifk_gbg", "win": "ifk_gbg", "by": "replay", "agg": (2, 2),
                 "legs": [L("jeunesse", "ifk_gbg", 1, 2), L("ifk_gbg", "jeunesse", 0, 1),
                          L("jeunesse", "ifk_gbg", 1, 5, venue="Gothenburg (play-off)")]},
                {"t1": "polonia", "t2": "mtk", "win": "mtk", "by": "aggregate", "agg": (0, 6),
                 "legs": [L("polonia", "mtk", 0, 3), L("mtk", "polonia", 3, 0)]},
                {"t1": "dos_utrecht", "t2": "sporting_cp", "win": "sporting_cp", "by": "aggregate", "agg": (4, 6),
                 "legs": [L("dos_utrecht", "sporting_cp", 3, 4), L("sporting_cp", "dos_utrecht", 2, 1)]},
                {"t1": "standard", "t2": "hearts", "win": "standard", "by": "aggregate", "agg": (6, 3),
                 "legs": [L("standard", "hearts", 5, 1), L("hearts", "standard", 2, 1)]},
                {"t1": "ards", "t2": "reims", "win": "reims", "by": "aggregate", "agg": (3, 10),
                 "legs": [L("ards", "reims", 1, 4, venue="Belfast (1st leg)"), L("reims", "ards", 6, 2)]},
                {"t1": "besiktas", "t2": "olympiakos", "win": "besiktas", "by": "walkover", "agg": None,
                 "legs": [], "note": "Olympiakos withdrew."},
                {"t1": "young_boys", "t2": "man_utd", "win": "young_boys", "by": "walkover", "agg": None,
                 "legs": [], "note": "Manchester United withdrew following the Munich air disaster."},
            ]},
            {"name": "First Round", "ties": [
                {"t1": "real_madrid", "t2": "besiktas", "win": "real_madrid", "by": "aggregate", "agg": (3, 1),
                 "legs": [L("real_madrid", "besiktas", 2, 0), L("besiktas", "real_madrid", 1, 1)]},
                {"t1": "wiener_sc", "t2": "dukla", "win": "wiener_sc", "by": "aggregate", "agg": (3, 2),
                 "legs": [L("wiener_sc", "dukla", 3, 1), L("dukla", "wiener_sc", 1, 0)]},
                {"t1": "wolves", "t2": "schalke", "win": "schalke", "by": "aggregate", "agg": (3, 4),
                 "legs": [L("wolves", "schalke", 2, 2), L("schalke", "wolves", 2, 1)]},
                {"t1": "atletico", "t2": "cdna_sofia", "win": "atletico", "by": "replay", "agg": (2, 2),
                 "legs": [L("atletico", "cdna_sofia", 2, 1), L("cdna_sofia", "atletico", 1, 0),
                          L("atletico", "cdna_sofia", 3, 1, venue="Geneva (play-off)", aet=True)]},
                {"t1": "mtk", "t2": "young_boys", "win": "young_boys", "by": "aggregate", "agg": (2, 6),
                 "legs": [L("mtk", "young_boys", 1, 2), L("young_boys", "mtk", 4, 1)]},
                {"t1": "ifk_gbg", "t2": "wismut", "win": "wismut", "by": "aggregate", "agg": (2, 6),
                 "legs": [L("ifk_gbg", "wismut", 2, 2), L("wismut", "ifk_gbg", 4, 0, venue="Aue (2nd leg)")]},
                {"t1": "sporting_cp", "t2": "standard", "win": "standard", "by": "aggregate", "agg": (2, 6),
                 "legs": [L("sporting_cp", "standard", 2, 3), L("standard", "sporting_cp", 3, 0)]},
                {"t1": "reims", "t2": "hps_helsinki", "win": "reims", "by": "aggregate", "agg": (7, 0),
                 "legs": [L("reims", "hps_helsinki", 4, 0),
                          L("hps_helsinki", "reims", 0, 3, venue="Rouen (2nd leg relocated)")]},
            ]},
            {"name": "Quarter-Finals", "ties": [
                {"t1": "wiener_sc", "t2": "real_madrid", "win": "real_madrid", "by": "aggregate", "agg": (1, 7),
                 "legs": [L("wiener_sc", "real_madrid", 0, 0), L("real_madrid", "wiener_sc", 7, 1)]},
                {"t1": "atletico", "t2": "schalke", "win": "atletico", "by": "aggregate", "agg": (4, 1),
                 "legs": [L("atletico", "schalke", 3, 0), L("schalke", "atletico", 1, 1)]},
                {"t1": "young_boys", "t2": "wismut", "win": "young_boys", "by": "replay", "agg": (2, 2),
                 "legs": [L("young_boys", "wismut", 2, 2), L("wismut", "young_boys", 0, 0, venue="Aue (2nd leg)"),
                          L("young_boys", "wismut", 2, 1, venue="Amsterdam (play-off)")]},
                {"t1": "standard", "t2": "reims", "win": "reims", "by": "aggregate", "agg": (2, 3),
                 "legs": [L("standard", "reims", 2, 0), L("reims", "standard", 3, 0)]},
            ]},
            {"name": "Semi-Finals", "ties": [
                {"t1": "real_madrid", "t2": "atletico", "win": "real_madrid", "by": "replay", "agg": (2, 2),
                 "legs": [L("real_madrid", "atletico", 2, 1), L("atletico", "real_madrid", 1, 0),
                          L("real_madrid", "atletico", 2, 1, venue="Zaragoza (play-off)")]},
                {"t1": "young_boys", "t2": "reims", "win": "reims", "by": "aggregate", "agg": (1, 3),
                 "legs": [L("young_boys", "reims", 1, 0),
                          L("reims", "young_boys", 3, 0, venue="Paris (2nd leg relocated)")]},
            ]},
            {"name": "Final", "ties": [
                {"t1": "real_madrid", "t2": "reims", "win": "real_madrid", "by": "single_match", "agg": (2, 0),
                 "legs": [L("real_madrid", "reims", 2, 0, venue="Neckarstadion, Stuttgart",
                            date="1959-06-03", att=80000, ref="Albert Dusch (West Germany)")]},
            ]},
        ],
    },

    # =====================================================================
    # 1959-60 — the 7-3 Hampden final
    # =====================================================================
    {
        "lineage": "European Cup", "season_label": "1959-60", "start_year": 1959,
        "competition_name": "European Cup",
        "winner": "real_madrid", "runner_up": "eintracht", "away_goals_active": False,
        "notes": "Real Madrid's fifth in a row, sealed by the 7-3 win over Eintracht Frankfurt at Hampden Park.",
        "rounds": [
            {"name": "Qualifying Round", "ties": [
                {"t1": "jeunesse", "t2": "lks_lodz", "win": "jeunesse", "by": "aggregate", "agg": (6, 2),
                 "legs": [L("jeunesse", "lks_lodz", 5, 0), L("lks_lodz", "jeunesse", 2, 1)]},
                {"t1": "fenerbahce", "t2": "csepel", "win": "fenerbahce", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("fenerbahce", "csepel", 1, 1), L("csepel", "fenerbahce", 2, 3)]},
                {"t1": "nice", "t2": "shamrock", "win": "nice", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("nice", "shamrock", 3, 2), L("shamrock", "nice", 1, 1)]},
                {"t1": "vorwarts", "t2": "wolves", "win": "wolves", "by": "aggregate", "agg": (2, 3),
                 "legs": [L("vorwarts", "wolves", 2, 1), L("wolves", "vorwarts", 2, 0)]},
                {"t1": "olympiakos", "t2": "milan", "win": "milan", "by": "aggregate", "agg": (3, 5),
                 "legs": [L("olympiakos", "milan", 2, 2), L("milan", "olympiakos", 3, 1)]},
                {"t1": "cdna_sofia", "t2": "barcelona", "win": "barcelona", "by": "aggregate", "agg": (4, 8),
                 "legs": [L("cdna_sofia", "barcelona", 2, 2), L("barcelona", "cdna_sofia", 6, 2)]},
                {"t1": "rangers", "t2": "anderlecht", "win": "rangers", "by": "aggregate", "agg": (7, 2),
                 "legs": [L("rangers", "anderlecht", 5, 2), L("anderlecht", "rangers", 0, 2)]},
                {"t1": "slovan", "t2": "porto", "win": "slovan", "by": "aggregate", "agg": (4, 1),
                 "legs": [L("slovan", "porto", 2, 1), L("porto", "slovan", 0, 2)],
                 "note": "Slovan competed as ČH Bratislava this season."},
                {"t1": "linfield", "t2": "ifk_gbg", "win": "ifk_gbg", "by": "aggregate", "agg": (3, 7),
                 "legs": [L("linfield", "ifk_gbg", 2, 1), L("ifk_gbg", "linfield", 6, 1)]},
                {"t1": "wiener_sc", "t2": "petrolul", "win": "wiener_sc", "by": "aggregate", "agg": (2, 1),
                 "legs": [L("wiener_sc", "petrolul", 0, 0), L("petrolul", "wiener_sc", 1, 2)]},
                {"t1": "eintracht", "t2": "kups", "win": "eintracht", "by": "walkover", "agg": None,
                 "legs": [], "note": "KuPS Kuopio withdrew."},
            ]},
            {"name": "First Round", "ties": [
                {"t1": "real_madrid", "t2": "jeunesse", "win": "real_madrid", "by": "aggregate", "agg": (12, 2),
                 "legs": [L("real_madrid", "jeunesse", 7, 0),
                          L("jeunesse", "real_madrid", 2, 5, venue="Luxembourg City (2nd leg relocated)")]},
                {"t1": "fenerbahce", "t2": "nice", "win": "nice", "by": "replay", "agg": (3, 3),
                 "legs": [L("fenerbahce", "nice", 2, 1), L("nice", "fenerbahce", 2, 1),
                          L("fenerbahce", "nice", 1, 5, venue="Geneva (play-off)")]},
                {"t1": "red_star", "t2": "wolves", "win": "wolves", "by": "aggregate", "agg": (1, 4),
                 "legs": [L("red_star", "wolves", 1, 1), L("wolves", "red_star", 3, 0)]},
                {"t1": "milan", "t2": "barcelona", "win": "barcelona", "by": "aggregate", "agg": (1, 7),
                 "legs": [L("milan", "barcelona", 0, 2), L("barcelona", "milan", 5, 1)]},
                {"t1": "rangers", "t2": "slovan", "win": "rangers", "by": "aggregate", "agg": (5, 4),
                 "legs": [L("rangers", "slovan", 4, 3), L("slovan", "rangers", 1, 1)]},
                {"t1": "sparta_rot", "t2": "ifk_gbg", "win": "sparta_rot", "by": "replay", "agg": (4, 4),
                 "legs": [L("sparta_rot", "ifk_gbg", 3, 1), L("ifk_gbg", "sparta_rot", 3, 1),
                          L("sparta_rot", "ifk_gbg", 3, 1, venue="Bremen (play-off)")]},
                {"t1": "b1909_odense", "t2": "wiener_sc", "win": "wiener_sc", "by": "aggregate", "agg": (2, 5),
                 "legs": [L("b1909_odense", "wiener_sc", 0, 3), L("wiener_sc", "b1909_odense", 2, 2)]},
                {"t1": "young_boys", "t2": "eintracht", "win": "eintracht", "by": "aggregate", "agg": (2, 5),
                 "legs": [L("young_boys", "eintracht", 1, 4), L("eintracht", "young_boys", 1, 1)]},
            ]},
            {"name": "Quarter-Finals", "ties": [
                {"t1": "nice", "t2": "real_madrid", "win": "real_madrid", "by": "aggregate", "agg": (3, 6),
                 "legs": [L("nice", "real_madrid", 3, 2), L("real_madrid", "nice", 4, 0)]},
                {"t1": "barcelona", "t2": "wolves", "win": "barcelona", "by": "aggregate", "agg": (9, 2),
                 "legs": [L("barcelona", "wolves", 4, 0), L("wolves", "barcelona", 2, 5)]},
                {"t1": "sparta_rot", "t2": "rangers", "win": "rangers", "by": "replay", "agg": (3, 3),
                 "legs": [L("sparta_rot", "rangers", 2, 3), L("rangers", "sparta_rot", 0, 1),
                          L("sparta_rot", "rangers", 2, 3, venue="London, Highbury (play-off)")]},
                {"t1": "eintracht", "t2": "wiener_sc", "win": "eintracht", "by": "aggregate", "agg": (3, 2),
                 "legs": [L("eintracht", "wiener_sc", 2, 1), L("wiener_sc", "eintracht", 1, 1)]},
            ]},
            {"name": "Semi-Finals", "ties": [
                {"t1": "real_madrid", "t2": "barcelona", "win": "real_madrid", "by": "aggregate", "agg": (6, 2),
                 "legs": [L("real_madrid", "barcelona", 3, 1), L("barcelona", "real_madrid", 1, 3)]},
                {"t1": "eintracht", "t2": "rangers", "win": "eintracht", "by": "aggregate", "agg": (12, 4),
                 "legs": [L("eintracht", "rangers", 6, 1), L("rangers", "eintracht", 3, 6)]},
            ]},
            {"name": "Final", "ties": [
                {"t1": "real_madrid", "t2": "eintracht", "win": "real_madrid", "by": "single_match", "agg": (7, 3),
                 "legs": [L("real_madrid", "eintracht", 7, 3, venue="Hampden Park, Glasgow",
                            date="1960-05-18", att=135000, ref="Jack Mowat (Scotland)")]},
            ]},
        ],
    },


    # =====================================================================
    # 1960-61 - Benfica's first European Cup
    # =====================================================================
    {
        "lineage": "European Cup", "season_label": "1960-61", "start_year": 1960,
        "competition_name": "European Cup",
        "winner": "benfica", "runner_up": "barcelona", "away_goals_active": False,
        "notes": "Benfica's first European Cup; Real Madrid's five-in-a-row ended by Barcelona in the first round.",
        "rounds": [
            {"name": "Preliminary Round", "ties": [
                {"t1": "hearts", "t2": "benfica", "win": "benfica", "by": "aggregate", "agg": (1, 5),
                 "legs": [L("hearts", "benfica", 1, 2), L("benfica", "hearts", 3, 0)]},
                {"t1": "red_star", "t2": "ujpest", "win": "ujpest", "by": "aggregate", "agg": (1, 5),
                 "legs": [L("red_star", "ujpest", 1, 2), L("ujpest", "red_star", 3, 0)]},
                {"t1": "fredrikstad", "t2": "ajax", "win": "fredrikstad", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("fredrikstad", "ajax", 4, 3), L("ajax", "fredrikstad", 0, 0)]},
                {"t1": "agf", "t2": "cwks_warsaw", "win": "agf", "by": "aggregate", "agg": (3, 1),
                 "legs": [L("agf", "cwks_warsaw", 3, 0), L("cwks_warsaw", "agf", 1, 0)],
                 "note": "Legia Warsaw (CWKS) competed under the Legia name this season."},
                {"t1": "juventus", "t2": "cdna_sofia", "win": "cdna_sofia", "by": "aggregate", "agg": (3, 4),
                 "legs": [L("juventus", "cdna_sofia", 2, 0), L("cdna_sofia", "juventus", 4, 1)]},
                {"t1": "hifk", "t2": "ifk_malmo", "win": "ifk_malmo", "by": "aggregate", "agg": (2, 5),
                 "legs": [L("hifk", "ifk_malmo", 1, 3), L("ifk_malmo", "hifk", 2, 1)]},
                {"t1": "rapid_wien", "t2": "besiktas", "win": "rapid_wien", "by": "aggregate", "agg": (4, 1),
                 "legs": [L("rapid_wien", "besiktas", 4, 0), L("besiktas", "rapid_wien", 1, 0)]},
                {"t1": "limerick", "t2": "young_boys", "win": "young_boys", "by": "aggregate", "agg": (2, 9),
                 "legs": [L("limerick", "young_boys", 0, 5), L("young_boys", "limerick", 4, 2)]},
                {"t1": "reims", "t2": "jeunesse", "win": "reims", "by": "aggregate", "agg": (11, 1),
                 "legs": [L("reims", "jeunesse", 6, 1), L("jeunesse", "reims", 0, 5)]},
                {"t1": "barcelona", "t2": "lierse", "win": "barcelona", "by": "aggregate", "agg": (5, 0),
                 "legs": [L("barcelona", "lierse", 2, 0),
                          L("lierse", "barcelona", 0, 3, venue="Brussels (2nd leg relocated)")]},
                {"t1": "wismut", "t2": "glenavon", "win": "wismut", "by": "walkover", "agg": None,
                 "legs": [], "note": "Glenavon withdrew; Wismut Karl-Marx-Stadt walkover."},
                {"t1": "hradec", "t2": "cca_buc", "win": "hradec", "by": "walkover", "agg": None,
                 "legs": [],
                 "note": "CCA București withdrew by decision of the Romanian federation."},
            ]},
            {"name": "First Round", "ties": [
                {"t1": "benfica", "t2": "ujpest", "win": "benfica", "by": "aggregate", "agg": (7, 4),
                 "legs": [L("benfica", "ujpest", 6, 2), L("ujpest", "benfica", 2, 1)]},
                {"t1": "agf", "t2": "fredrikstad", "win": "agf", "by": "aggregate", "agg": (4, 0),
                 "legs": [L("agf", "fredrikstad", 3, 0),
                          L("fredrikstad", "agf", 0, 1, venue="Oslo (2nd leg relocated)")]},
                {"t1": "ifk_malmo", "t2": "cdna_sofia", "win": "ifk_malmo", "by": "aggregate", "agg": (2, 1),
                 "legs": [L("ifk_malmo", "cdna_sofia", 1, 0), L("cdna_sofia", "ifk_malmo", 1, 1)]},
                {"t1": "rapid_wien", "t2": "wismut", "win": "rapid_wien", "by": "replay", "agg": (3, 3),
                 "legs": [L("rapid_wien", "wismut", 3, 1), L("wismut", "rapid_wien", 2, 0),
                          L("rapid_wien", "wismut", 1, 0, venue="Basel (play-off)")]},
                {"t1": "young_boys", "t2": "hamburg", "win": "hamburg", "by": "aggregate", "agg": (3, 8),
                 "legs": [L("young_boys", "hamburg", 0, 5), L("hamburg", "young_boys", 3, 3)]},
                {"t1": "burnley", "t2": "reims", "win": "burnley", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("burnley", "reims", 2, 0),
                          L("reims", "burnley", 3, 2, venue="Paris (2nd leg relocated)")]},
                {"t1": "hradec", "t2": "panathinaikos", "win": "hradec", "by": "aggregate", "agg": (1, 0),
                 "legs": [L("hradec", "panathinaikos", 1, 0), L("panathinaikos", "hradec", 0, 0)]},
                {"t1": "real_madrid", "t2": "barcelona", "win": "barcelona", "by": "aggregate", "agg": (3, 4),
                 "legs": [L("real_madrid", "barcelona", 2, 2), L("barcelona", "real_madrid", 2, 1)]},
            ]},
            {"name": "Quarter-Finals", "ties": [
                {"t1": "benfica", "t2": "agf", "win": "benfica", "by": "aggregate", "agg": (7, 2),
                 "legs": [L("benfica", "agf", 3, 1), L("agf", "benfica", 1, 4)]},
                {"t1": "rapid_wien", "t2": "ifk_malmo", "win": "rapid_wien", "by": "aggregate", "agg": (4, 0),
                 "legs": [L("rapid_wien", "ifk_malmo", 2, 0), L("ifk_malmo", "rapid_wien", 0, 2)]},
                {"t1": "burnley", "t2": "hamburg", "win": "hamburg", "by": "aggregate", "agg": (4, 5),
                 "legs": [L("burnley", "hamburg", 3, 1), L("hamburg", "burnley", 4, 1)]},
                {"t1": "barcelona", "t2": "hradec", "win": "barcelona", "by": "aggregate", "agg": (5, 1),
                 "legs": [L("barcelona", "hradec", 4, 0),
                          L("hradec", "barcelona", 1, 1, venue="Prague (2nd leg)")]},
            ]},
            {"name": "Semi-Finals", "ties": [
                {"t1": "benfica", "t2": "rapid_wien", "win": "benfica", "by": "aggregate", "agg": (4, 1),
                 "legs": [L("benfica", "rapid_wien", 3, 0), L("rapid_wien", "benfica", 1, 1)],
                 "note": "2nd leg abandoned after 88 minutes; result stood."},
                {"t1": "barcelona", "t2": "hamburg", "win": "barcelona", "by": "replay", "agg": (2, 2),
                 "legs": [L("barcelona", "hamburg", 1, 0), L("hamburg", "barcelona", 2, 1),
                          L("barcelona", "hamburg", 1, 0, venue="Brussels (play-off)")]},
            ]},
            {"name": "Final", "ties": [
                {"t1": "benfica", "t2": "barcelona", "win": "benfica", "by": "single_match", "agg": (3, 2),
                 "legs": [L("benfica", "barcelona", 3, 2, venue="Wankdorf Stadium, Berne",
                            date="1961-05-31", att=28000, ref="Gottfried Dienst (Switzerland)")]},
            ]},
        ],
    },


    # =====================================================================
    # 1961-62 — Benfica retain the European Cup
    # =====================================================================
    {
        "lineage": "European Cup", "season_label": "1961-62", "start_year": 1961,
        "competition_name": "European Cup",
        "winner": "benfica", "runner_up": "real_madrid", "away_goals_active": False,
        "notes": "Benfica retained the European Cup, beating Real Madrid 5-3 in Amsterdam. Holders Benfica, Fenerbahçe and Haka received byes into the First Round. Away-goals rule not yet in use.",
        "rounds": [
            {"name": "Preliminary Round", "ties": [
                {"t1": "cca_buc", "t2": "austria_wien", "win": "austria_wien", "by": "aggregate", "agg": (0, 2),
                 "legs": [L("cca_buc", "austria_wien", 0, 0, date="1961-09-21"),
                          L("austria_wien", "cca_buc", 2, 0, date="1961-09-28")]},
                {"t1": "nurnberg", "t2": "drumcondra", "win": "nurnberg", "by": "aggregate", "agg": (9, 1),
                 "legs": [L("nurnberg", "drumcondra", 5, 0, date="1961-08-23"),
                          L("drumcondra", "nurnberg", 1, 4, date="1961-09-13")]},
                {"t1": "servette", "t2": "hibernians_malta", "win": "servette", "by": "aggregate", "agg": (7, 1),
                 "legs": [L("servette", "hibernians_malta", 5, 0, date="1961-09-06"),
                          L("hibernians_malta", "servette", 1, 2, date="1961-09-20")]},
                {"t1": "cdna_sofia", "t2": "dukla", "win": "dukla", "by": "aggregate", "agg": (5, 6),
                 "legs": [L("cdna_sofia", "dukla", 4, 4, date="1961-09-06"),
                          L("dukla", "cdna_sofia", 2, 1, date="1961-09-13")]},
                {"t1": "ifk_gbg", "t2": "feyenoord", "win": "feyenoord", "by": "aggregate", "agg": (2, 11),
                 "legs": [L("ifk_gbg", "feyenoord", 0, 3, date="1961-09-05"),
                          L("feyenoord", "ifk_gbg", 8, 2, date="1961-09-13")]},
                {"t1": "gornik", "t2": "tottenham", "win": "tottenham", "by": "aggregate", "agg": (5, 10),
                 "legs": [L("gornik", "tottenham", 4, 2, venue="Chorzów (1st leg)", date="1961-09-13"),
                          L("tottenham", "gornik", 8, 1, date="1961-09-20")],
                 "note": "1st leg played in Chorzów."},
                {"t1": "standard", "t2": "fredrikstad", "win": "standard", "by": "aggregate", "agg": (4, 1),
                 "legs": [L("standard", "fredrikstad", 2, 1, date="1961-09-06"),
                          L("fredrikstad", "standard", 0, 2, venue="Oslo (2nd leg relocated)", date="1961-09-20")]},
                {"t1": "vorwarts", "t2": "linfield", "win": "vorwarts", "by": "walkover", "agg": None,
                 "legs": [],
                 "note": "Linfield withdrew after a 3-0 first leg (1961-08-30). Vorwärts were denied "
                         "UK visas and Linfield could not afford to travel to an alternative venue. "
                         "RSSSF records the played 3-0, but with only one leg contested it is stored "
                         "here as a walkover rather than a completed two-leg aggregate."},
                {"t1": "monaco", "t2": "rangers", "win": "rangers", "by": "aggregate", "agg": (4, 6),
                 "legs": [L("monaco", "rangers", 2, 3, date="1961-09-05"),
                          L("rangers", "monaco", 3, 2, date="1961-09-12")]},
                {"t1": "sporting_cp", "t2": "partizan", "win": "partizan", "by": "aggregate", "agg": (1, 3),
                 "legs": [L("sporting_cp", "partizan", 1, 1, date="1961-09-13"),
                          L("partizan", "sporting_cp", 2, 0, date="1961-09-20")]},
                {"t1": "panathinaikos", "t2": "juventus", "win": "juventus", "by": "aggregate", "agg": (2, 3),
                 "legs": [L("panathinaikos", "juventus", 1, 1, date="1961-09-20"),
                          L("juventus", "panathinaikos", 2, 1, date="1961-09-27")]},
                {"t1": "spora", "t2": "b1913", "win": "b1913", "by": "aggregate", "agg": (2, 15),
                 "legs": [L("spora", "b1913", 0, 6, date="1961-09-07"),
                          L("b1913", "spora", 9, 2, date="1961-09-13")]},
                {"t1": "vasas", "t2": "real_madrid", "win": "real_madrid", "by": "aggregate", "agg": (1, 5),
                 "legs": [L("vasas", "real_madrid", 0, 2, date="1961-09-06"),
                          L("real_madrid", "vasas", 3, 1, date="1961-09-20")]},
            ]},
            {"name": "First Round", "ties": [
                {"t1": "austria_wien", "t2": "benfica", "win": "benfica", "by": "aggregate", "agg": (2, 6),
                 "legs": [L("austria_wien", "benfica", 1, 1, date="1961-10-31"),
                          L("benfica", "austria_wien", 5, 1, date="1961-11-08")]},
                {"t1": "fenerbahce", "t2": "nurnberg", "win": "nurnberg", "by": "aggregate", "agg": (1, 3),
                 "legs": [L("fenerbahce", "nurnberg", 1, 2, date="1961-10-18"),
                          L("nurnberg", "fenerbahce", 1, 0, date="1961-12-03")]},
                {"t1": "servette", "t2": "dukla", "win": "dukla", "by": "aggregate", "agg": (4, 5),
                 "legs": [L("servette", "dukla", 4, 3, date="1961-11-05"),
                          L("dukla", "servette", 2, 0, date="1961-11-22")]},
                {"t1": "feyenoord", "t2": "tottenham", "win": "tottenham", "by": "aggregate", "agg": (2, 4),
                 "legs": [L("feyenoord", "tottenham", 1, 3, date="1961-11-01"),
                          L("tottenham", "feyenoord", 1, 1, date="1961-11-15")]},
                {"t1": "vorwarts", "t2": "rangers", "win": "rangers", "by": "aggregate", "agg": (2, 6),
                 "legs": [L("vorwarts", "rangers", 1, 2, date="1961-11-15"),
                          L("rangers", "vorwarts", 4, 1, venue="Malmö (2nd leg relocated)", date="1961-11-23")],
                 "note": "2nd leg in Malmö after Vorwärts were refused UK entry visas; abandoned at 1-0 to Rangers at half-time on 22 November due to fog and replayed in full on 23 November."},
                {"t1": "standard", "t2": "haka", "win": "standard", "by": "aggregate", "agg": (7, 1),
                 "legs": [L("standard", "haka", 5, 1, date="1961-10-24"),
                          L("haka", "standard", 0, 2, date="1961-11-02")]},
                {"t1": "partizan", "t2": "juventus", "win": "juventus", "by": "aggregate", "agg": (1, 7),
                 "legs": [L("partizan", "juventus", 1, 2, date="1961-11-08"),
                          L("juventus", "partizan", 5, 0, date="1961-11-15")]},
                {"t1": "b1913", "t2": "real_madrid", "win": "real_madrid", "by": "aggregate", "agg": (0, 12),
                 "legs": [L("b1913", "real_madrid", 0, 3, date="1961-10-18"),
                          L("real_madrid", "b1913", 9, 0, date="1961-10-25")]},
            ]},
            {"name": "Quarter-Finals", "ties": [
                {"t1": "nurnberg", "t2": "benfica", "win": "benfica", "by": "aggregate", "agg": (3, 7),
                 "legs": [L("nurnberg", "benfica", 3, 1, date="1962-02-01"),
                          L("benfica", "nurnberg", 6, 0, date="1962-02-22")]},
                {"t1": "dukla", "t2": "tottenham", "win": "tottenham", "by": "aggregate", "agg": (2, 4),
                 "legs": [L("dukla", "tottenham", 1, 0, date="1962-02-14"),
                          L("tottenham", "dukla", 4, 1, date="1962-02-21")]},
                {"t1": "standard", "t2": "rangers", "win": "standard", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("standard", "rangers", 4, 1, date="1962-02-07"),
                          L("rangers", "standard", 2, 0, date="1962-02-14")]},
                {"t1": "juventus", "t2": "real_madrid", "win": "real_madrid", "by": "replay", "agg": (1, 1),
                 "legs": [L("juventus", "real_madrid", 0, 1, date="1962-02-14"),
                          L("real_madrid", "juventus", 0, 1, date="1962-02-21"),
                          L("real_madrid", "juventus", 3, 1, venue="Paris (play-off)", date="1962-02-28")],
                 "note": "Play-off in Paris; Real Madrid designated home side."},
            ]},
            {"name": "Semi-Finals", "ties": [
                {"t1": "real_madrid", "t2": "standard", "win": "real_madrid", "by": "aggregate", "agg": (6, 0),
                 "legs": [L("real_madrid", "standard", 4, 0, date="1962-03-22"),
                          L("standard", "real_madrid", 0, 2, date="1962-04-12")]},
                {"t1": "benfica", "t2": "tottenham", "win": "benfica", "by": "aggregate", "agg": (4, 3),
                 "legs": [L("benfica", "tottenham", 3, 1, date="1962-03-21"),
                          L("tottenham", "benfica", 2, 1, date="1962-04-05")]},
            ]},
            {"name": "Final", "ties": [
                {"t1": "benfica", "t2": "real_madrid", "win": "benfica", "by": "single_match", "agg": (5, 3),
                 "legs": [L("benfica", "real_madrid", 5, 3, venue="Olympisch Stadion, Amsterdam",
                            date="1962-05-02", att=65000, ref="Leo Horn (Netherlands)")]},
            ]},
        ],
    },

    # =====================================================================
    # 1960-61 - inaugural European Cup Winners' Cup
    # =====================================================================
    {
        "lineage": "European Cup Winners' Cup", "season_label": "1960-61", "start_year": 1960,
        "competition_name": "European Cup Winners' Cup",
        "winner": "fiorentina", "runner_up": "rangers", "away_goals_active": False,
        "notes": "Inaugural Cup Winners' Cup. Only final decided over two legs.",
        "rounds": [
            {"name": "Qualifying Round", "ties": [
                {"t1": "vorwarts", "t2": "red_star_brno", "win": "red_star_brno", "by": "aggregate", "agg": (2, 3),
                 "legs": [L("vorwarts", "red_star_brno", 2, 1), L("red_star_brno", "vorwarts", 2, 0)]},
                {"t1": "rangers", "t2": "ferencvaros", "win": "rangers", "by": "aggregate", "agg": (5, 4),
                 "legs": [L("rangers", "ferencvaros", 4, 2), L("ferencvaros", "rangers", 2, 1)]},
            ]},
            {"name": "Quarter-Finals", "ties": [
                {"t1": "lucerne", "t2": "fiorentina", "win": "fiorentina", "by": "aggregate", "agg": (2, 9),
                 "legs": [L("lucerne", "fiorentina", 0, 3), L("fiorentina", "lucerne", 6, 2)]},
                {"t1": "red_star_brno", "t2": "dinamo_zagreb", "win": "dinamo_zagreb", "by": "aggregate", "agg": (0, 2),
                 "legs": [L("red_star_brno", "dinamo_zagreb", 0, 0), L("dinamo_zagreb", "red_star_brno", 2, 0)]},
                {"t1": "austria_wien", "t2": "wolves", "win": "wolves", "by": "aggregate", "agg": (2, 5),
                 "legs": [L("austria_wien", "wolves", 2, 0), L("wolves", "austria_wien", 5, 0)]},
                {"t1": "gladbach", "t2": "rangers", "win": "rangers", "by": "aggregate", "agg": (0, 11),
                 "legs": [L("gladbach", "rangers", 0, 3, venue="Düsseldorf (1st leg relocated)"),
                          L("rangers", "gladbach", 8, 0)]},
            ]},
            {"name": "Semi-Finals", "ties": [
                {"t1": "fiorentina", "t2": "dinamo_zagreb", "win": "fiorentina", "by": "aggregate", "agg": (4, 2),
                 "legs": [L("fiorentina", "dinamo_zagreb", 3, 0), L("dinamo_zagreb", "fiorentina", 2, 1)]},
                {"t1": "rangers", "t2": "wolves", "win": "rangers", "by": "aggregate", "agg": (3, 1),
                 "legs": [L("rangers", "wolves", 2, 0), L("wolves", "rangers", 1, 1)]},
            ]},
            {"name": "Final", "ties": [
                {"t1": "rangers", "t2": "fiorentina", "win": "fiorentina", "by": "aggregate", "agg": (1, 4),
                 "legs": [
                     L("rangers", "fiorentina", 0, 2, venue="Ibrox Stadium, Glasgow",
                       date="1961-05-17", att=80000, ref="Carl Erich Steiner (Austria)"),
                     L("fiorentina", "rangers", 2, 1, venue="Stadio Comunale, Florence",
                       date="1961-05-27", att=50000, ref="Vilmos Hernádi (Hungary)"),
                 ]},
            ]},
        ],
    },

]
